childLabels:
  - group: kro.run
    version: v1alpha1
    kind: Application
    matchLabels:
      kro.run/instance-name: "{{ .metadata.name }}"
    managedGVKs:
      - group: apps
        version: v1
        resource: deployments
      - group: ""
        version: v1
        resource: services
