version: "3.8"

services:
  cerbos:
    container_name: cerbos
    image: ghcr.io/cerbos/cerbos:latest
    ports:
      - "3592:3592"
      - "3593:3593"
    volumes:
      - ./internal/cerbos/config:/config
      - ./internal/cerbos/policies:/policies
    command: server --config=/config/conf.yaml
