{{- if (.Values.global).enableNetworkPolicies -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cyclops-ui
  namespace: cyclops
spec:
  podSelector:
    matchLabels:
      app: cyclops-ui
  ingress:
    - {}
  egress:
    - {}
  policyTypes:
    - Ingress
    - Egress
{{- end }}
