apiVersion: v1
kind: Service
metadata:
  name: cyclops-ui
  namespace: {{ include "cyclops.namespace" . | quote }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 80
      protocol: TCP
  selector:
    app: cyclops-ui
