/* eslint-disable */
window.__RUNTIME_CONFIG__ = {
    NODE_ENV: '${NODE_ENV}',
    REACT_APP_CYCLOPS_CTRL_HOST: '${REACT_APP_CYCLOPS_CTRL_HOST}',
    REACT_APP_DEFAULT_TEMPLATE_REPO: '${REACT_APP_DEFAULT_TEMPLATE_REPO}',
    REACT_APP_DEFAULT_TEMPLATE_PATH: '${REACT_APP_DEFAULT_TEMPLATE_PATH}',
    REACT_APP_DEFAULT_TEMPLATE_VERSION: '${REACT_APP_DEFAULT_TEMPLATE_VERSION}'
};
