apiVersion: v1
kind: Service
metadata:
  name: cyclops-ctrl
  namespace: {{ include "cyclops.namespace" . | quote }}
  labels:
    app: cyclops-ctrl
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: cyclops-ctrl
