---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cyclops-ui.com
  resources:
  - modules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cyclops-ui.com
  resources:
  - modules/finalizers
  verbs:
  - update
- apiGroups:
  - cyclops-ui.com
  resources:
  - modules/status
  verbs:
  - get
  - patch
  - update
