# This is a sample 'prometheus.yaml' file you can change this according to you needs.
# You can add this file path to the target of Prometheus

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cyclops-backend'
    static_configs:
      - targets: ['127.0.0.1:8888']
    metrics_path: /metrics